name: Schema Verification

on:
  push:
    branches: [main, develop]
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'

jobs:
  verify-schema:
    name: Verify Prisma Schema Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Verify Schema Synchronization
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run verify:schema

      - name: Comment on PR (if failed)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **Schema Drift Detected**

              The Prisma schema is not synchronized with the production database.

              **Fix:**
              \`\`\`bash
              npx prisma migrate dev --name sync_schema
              # or
              npx prisma db push
              \`\`\`

              Then commit the generated migration files.`
            })
